version: '3.7'

services:
    php-httpd:
        container_name: webserver
        build: php_httpd
        ports:
            - 80:80
        volumes:
            - "./website_content/:/var/www/html"
        networks:
            - net

    mariadb:
        container_name: database
        build: ./custom_db
        volumes:
            - mariadb-volume:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "1234"
            MYSQL_DATABASE: 'simple-website'
        ports:
          - 3306:3306
        networks:
            - net

    phpmyadmin:
        container_name: db_dashboard
        image: phpmyadmin/phpmyadmin
        links:
            - 'mariadb:db'
        ports:
            - 8081:80
        networks:
            - net

volumes:
    mariadb-volume:

networks:
  net:
