version: '3.7'

services:
    php-httpd:
        container_name: webserver
        build: php_httpd
        ports:
            - 80:80
        volumes:
            - "./website_content/:/var/www/html"

    mariadb:
        container_name: database
        image: mariadb:10.5.2
        volumes:
            - mariadb-volume:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "1234"
            MYSQL_DATABASE: 'simple-website'
        ports:
          - 3306:3306

    phpmyadmin:
        container_name: db_dashboard
        image: phpmyadmin/phpmyadmin
        links:
            - 'mariadb:db'
        ports:
            - 8081:80

volumes:
    mariadb-volume:
